spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/ourkitchen
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: ok1234
  jpa:
    hibernate:      ddl-auto: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  devtools:
    livereload:
      enabled: true
  flyway:
    enabled: true
    encoding: UTF-8