spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  profiles: local # log4j 설정
#  datasource:
#    platform: oracle
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url:
#    uername:
#    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hiberate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
        
      