# Generated by Django 2.2.8 on 2020-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floatingpop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
                ('dong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residentpop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('store_code', models.CharField(max_length=20)),
                ('mon_sales', models.IntegerField()),
                ('mon_sales_count', models.IntegerField()),
                ('weekdays_sales_rate', models.IntegerField()),
                ('weekend_sales_rate', models.IntegerField()),
                ('weekdays_sales_coount', models.IntegerField()),
                ('weekend_sales_count', models.IntegerField()),
                ('breakfast_sales', models.IntegerField()),
                ('lunch_sales', models.IntegerField()),
                ('dinner_sales', models.IntegerField()),
                ('men_sales_rate', models.IntegerField()),
                ('women_sales_rate', models.IntegerField()),
                ('dong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signgucd', models.IntegerField()),
                ('signgunm', models.CharField(max_length=20)),
                ('danger', models.CharField(max_length=20)),
                ('close', models.FloatField()),
                ('remain_term', models.FloatField()),
                ('plma', models.FloatField()),
            ],
        ),
    ]
