# Generated by Django 2.2.10 on 2020-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='move_pop',
        ),
        migrations.AddField(
            model_name='kitchen_info',
            name='add',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
