# Generated by Django 2.2.8 on 2020-04-12 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_industrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_info',
            name='add',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
