# Generated by Django 2.2.8 on 2020-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_kitchen_info_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floatingpop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residentpop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Start_up',
            new_name='Startup',
        ),
        migrations.DeleteModel(
            name='move_pop',
        ),
        migrations.DeleteModel(
            name='Movepop',
        ),
        migrations.RemoveField(
            model_name='reservation_time',
            name='kitchen_name',
        ),
        migrations.DeleteModel(
            name='stay_pop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.RenameField(
            model_name='kitchen_info',
            old_name='add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='kitchen_info',
            old_name='kitchen_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Reservation_time',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
