CREATE TABLE `tradingarea_sales_projection` (
	`id` INT(10) NULL DEFAULT NULL,
	`tradingarea_code` INT(10) NULL DEFAULT NULL,
	`tradingarea_name` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`service_code` INT(10) NULL DEFAULT NULL,
	`service_name` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`month_sales_amount` INT(10) NULL DEFAULT NULL,
	`month_sales_num` INT(10) NULL DEFAULT NULL,
	`weekday_sales_rate` INT(10) NULL DEFAULT NULL,
	`weekend_sales_rate` INT(10) NULL DEFAULT NULL,
	`mon_sales_rate` INT(10) NULL DEFAULT NULL,
	`tue_sales_rate` INT(10) NULL DEFAULT NULL,
	`wen_sales_rate` INT(10) NULL DEFAULT NULL,
	`thur_sales_rate` INT(10) NULL DEFAULT NULL,
	`fri_sales_rate` INT(10) NULL DEFAULT NULL,
	`sat_sales_rate` INT(10) NULL DEFAULT NULL,
	`sun_sales_rate` INT(10) NULL DEFAULT NULL,
	`time_0006_amount` INT(10) NULL DEFAULT NULL,
	`time_0611_amount` INT(10) NULL DEFAULT NULL,
	`time_1114_amount` INT(10) NULL DEFAULT NULL,
	`time_1417_amount` INT(10) NULL DEFAULT NULL,
	`time_1721_amount` INT(10) NULL DEFAULT NULL,
	`time_2124_amount` INT(10) NULL DEFAULT NULL,
	`women_sales_rate` INT(10) NULL DEFAULT NULL,
	`men_sales_rate` INT(10) NULL DEFAULT NULL,
	`age_10_rate` INT(10) NOT NULL,
	`age_20_rate` INT(10) NOT NULL,
	`age_30_rate` INT(10) NULL DEFAULT NULL,
	`age_40_rate` INT(10) NULL DEFAULT NULL,
	`age_50_rate` INT(10) NULL DEFAULT NULL,
	`age_60_rate` INT(10) NULL DEFAULT NULL,
	`weekday_sales_amount` INT(10) NULL DEFAULT NULL,
	`weekend_sales_amount` INT(10) NULL DEFAULT NULL,
	`mon_sales_amount` INT(10) NULL DEFAULT NULL,
	`tue_sales_amount` INT(10) NULL DEFAULT NULL,
	`wen_sales_amount` INT(10) NULL DEFAULT NULL,
	`thur_sales_amount` INT(10) NULL DEFAULT NULL,
	`fri_sales_amount` INT(10) NULL DEFAULT NULL,
	`sat_sales_amount` INT(10) NULL DEFAULT NULL,
	`sun_sales_amount` INT(10) NULL DEFAULT NULL,
	`times_0006_amount` INT(10) NULL DEFAULT NULL,
	`times_0611_amount` INT(10) NULL DEFAULT NULL,
	`times_1114_amount` INT(10) NULL DEFAULT NULL,
	`times_1417_amount` INT(10) NULL DEFAULT NULL,
	`times_1721_amount` INT(10) NULL DEFAULT NULL,
	`men_sales_amount` INT(10) NULL DEFAULT NULL,
	`women_sales_amount` INT(10) NULL DEFAULT NULL,
	`age_10_amount` INT(10) NULL DEFAULT NULL,
	`age_20_amount` INT(10) NULL DEFAULT NULL,
	`age_30_amount` INT(10) NULL DEFAULT NULL,
	`age_40_amount` INT(10) NULL DEFAULT NULL,
	`age_50_amount` INT(10) NULL DEFAULT NULL,
	`age_60_amount` INT(10) NULL DEFAULT NULL,
	`weekday_sales_num` INT(10) NULL DEFAULT NULL,
	`weekend_sales_num` INT(10) NULL DEFAULT NULL,
	`mon_sales_num` INT(10) NULL DEFAULT NULL,
	`tue_sales_num` INT(10) NULL DEFAULT NULL,
	`wen_sales_num` INT(10) NULL DEFAULT NULL,
	`thur_sales_num` INT(10) NULL DEFAULT NULL,
	`fri_sales_num` INT(10) NULL DEFAULT NULL,
	`sat_sales_num` INT(10) NULL DEFAULT NULL,
	`sun_sales_num` INT(10) NULL DEFAULT NULL,
	`times_0006_num` INT(10) NULL DEFAULT NULL,
	`times_0611_num` INT(10) NULL DEFAULT NULL,
	`times_1114_num` INT(10) NULL DEFAULT NULL,
	`times_1417_num` INT(10) NULL DEFAULT NULL,
	`times_1721_num` INT(10) NULL DEFAULT NULL,
	`times_2124_num` INT(10) NULL DEFAULT NULL,
	`men_sales_num` INT(10) NULL DEFAULT NULL,
	`women_sales_num` INT(10) NULL DEFAULT NULL,
	`age_10_sales_num` INT(10) NULL DEFAULT NULL,
	`age_20_sales_num` INT(10) NULL DEFAULT NULL,
	`age_30_sales_num` INT(10) NULL DEFAULT NULL,
	`age_40_sales_num` INT(10) NULL DEFAULT NULL,
	`age_50_sales_num` INT(10) NULL DEFAULT NULL,
	`age_60_sales_num` INT(10) NULL DEFAULT NULL,
	`store_num` INT(10) NULL DEFAULT NULL
)
COMMENT='상권 및 업종별 매출 현황'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
