CREATE TABLE KITCHEN_INFO (
    id INT NOT NULL auto_increment PRIMARY KEYNOT NULL,
    name VARCHAR(20) NOT NULL default ""NOT NULL,
    address VARCHAR(255) NOT NULL NOT NULL,
    certification VARCHAR(20) NOT NULLNOT NULL,
    lat float NOT NULLNOT NULL,
    lng float NOT NULLNOT NULL,
    capacity INT NOT NULLNOT NULL,
    user_id INT NOT NULLNOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id)
)